# Generated by Django 4.2.26 on 2025-11-25 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0011_matter_app_matter_status_2f2f4b_idx_and_more"),
        ("activity", "0004_expenseentry_app_expense_date_d2e25c_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenseentry",
            name="matter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="matters.matter",
            ),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="matter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="matters.matter",
            ),
        ),
    ]
