# Generated by Django 4.2.26 on 2025-11-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0005_alter_expenseentry_matter_alter_timeentry_matter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenseentry",
            name="comp",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="expenseentry",
            name="entered",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="comp",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="entered",
            field=models.BooleanField(default=False),
        ),
    ]
