# Generated by Django 4.2.26 on 2025-11-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trust", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="entered",
            field=models.BooleanField(default=False),
        ),
    ]
