# Generated by Django 4.2.26 on 2025-12-07 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlines", "0002_make_matter_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="importance",
            field=models.PositiveIntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
