# Generated by Django 4.2.26 on 2025-12-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlines", "0006_add_heading_to_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="outlineitem",
            name="highlight",
            field=models.BooleanField(default=False),
        ),
    ]
