# Generated by Django 4.2.26 on 2025-12-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0019_rename_fact_case_to_documents"),
        ("outlines", "0007_add_highlight_to_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="outlineitem",
            name="documents",
            field=models.ManyToManyField(
                blank=True, related_name="outline_items", to="case.document"
            ),
        ),
        migrations.AddField(
            model_name="outlineitem",
            name="highlights",
            field=models.ManyToManyField(
                blank=True, related_name="outline_items", to="case.highlight"
            ),
        ),
    ]
