# Generated by Django 4.2.26 on 2025-12-10 11:45

import django.core.validators
from django.db import migrations, models


def convert_heading_values(apps, schema_editor):
    """Convert heading=1 (was True) to heading=2, heading=0 (was False) to heading=None."""
    OutlineItem = apps.get_model("outlines", "OutlineItem")
    # Convert 1 (was True) to 2
    OutlineItem.objects.filter(heading=1).update(heading=2)
    # Convert 0 (was False) to None
    OutlineItem.objects.filter(heading=0).update(heading=None)


def convert_heading_values_reverse(apps, schema_editor):
    """Reverse: Convert heading>=2 to 1, heading=None to 0."""
    OutlineItem = apps.get_model("outlines", "OutlineItem")
    OutlineItem.objects.filter(heading__isnull=False).update(heading=1)
    OutlineItem.objects.filter(heading__isnull=True).update(heading=0)


class Migration(migrations.Migration):

    dependencies = [
        ("outlines", "0011_heading_items_to_top_level"),
    ]

    operations = [
        # First alter the field type (boolean 0/1 values are preserved as integers)
        migrations.AlterField(
            model_name="outlineitem",
            name="heading",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        # Then convert the data values
        migrations.RunPython(
            convert_heading_values,
            convert_heading_values_reverse,
        ),
    ]
