# Generated by Django 4.2.29 on 2026-03-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_checklistfolder_and_template_folder_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklisttemplate',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='historicalchecklisttemplate',
            name='is_active',
        ),
    ]
