# Generated by Django 4.2.22 on 2025-11-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_attorney",
            field=models.BooleanField(default=True),
        ),
    ]
