# Generated by Django 4.2.28 on 2026-03-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_customuser_digest_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="perm_all_matters",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="perm_financial",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="perm_intakes",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="perm_reports",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalcustomuser",
            name="perm_all_matters",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalcustomuser",
            name="perm_financial",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalcustomuser",
            name="perm_intakes",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalcustomuser",
            name="perm_reports",
            field=models.BooleanField(default=True),
        ),
    ]
