# Generated by Django 4.2.17 on 2024-12-13 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0001_initial"),
        ("billing", "0002_alter_invoice_discount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("detail", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="matters.matter"
                    ),
                ),
            ],
            options={
                "db_table": "app_billing_credit",
                "indexes": [
                    models.Index(
                        fields=["matter"], name="app_billing_matter__17a947_idx"
                    )
                ],
            },
        ),
    ]
