# Generated by Django 4.2.26 on 2025-11-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_normalize_phone_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="email2",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
