# Generated by Django 4.2.29 on 2026-03-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='item_type',
            field=models.CharField(choices=[('item', 'Item'), ('section', 'Section')], default='item', max_length=10),
        ),
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='item_type',
            field=models.CharField(choices=[('item', 'Item'), ('section', 'Section')], default='item', max_length=10),
        ),
    ]
