from django.urls import path

from apps.case.views import (
    add_highlight,
    add_label,
    add_label_to,
    bulk_documents_update,
    clear_document_selection,
    delete_highlight,
    delete_label,
    document_category,
    document_date,
    document_importance,
    document_proceeding,
    document_row,
    document_viewer,
    documents_add,
    documents_delete,
    documents_edit,
    documents_edit_name,
    documents_filter,
    documents_filter_category,
    documents_filter_importance,
    documents_filter_keyword,
    documents_filter_label,
    documents_list,
    documents_sort,
    download_document,
    edit_highlight,
    edit_label,
    fact_add_source,
    fact_importance,
    fact_remove_source,
    fact_sources_modal,
    fact_sources_search,
    facts_add,
    facts_delete,
    facts_edit,
    facts_edit_description,
    facts_filter,
    facts_filter_importance,
    facts_filter_keyword,
    facts_index,
    facts_list,
    facts_pdf,
    facts_print,
    facts_sort,
    facts_update_description,
    get_proceedings_and_labels,
    highlight_importance,
    highlight_link,
    highlights_filter,
    highlights_filter_default,
    highlights_filter_document,
    highlights_filter_importance,
    highlights_filter_keyword,
    highlights_filter_sort,
    highlights_for_document,
    highlights_index,
    highlights_list,
    index,
    labels_apply_modal,
    labels_create_and_apply,
    labels_filter,
    labels_index,
    labels_list,
    labels_search,
    labels_sort,
    ocr_badge,
    ocr_status,
    remove_label_from,
    retry_ocr,
    search_clear,
    search_filter,
    search_filter_type,
    search_index,
    search_list,
    search_query,
    search_results,
    select_matter,
    serve_document,
    toggle_document_select,
)

app_name = "case"

urlpatterns = [
    # Documents (document list subtab)
    path("documents/", index, name="index"),
    path("documents/list/", documents_list, name="documents-list"),
    path(
        "documents/select-matter/<int:matter_id>/", select_matter, name="select-matter"
    ),
    path("documents/add/", documents_add, name="documents-add"),
    path(
        "documents/add/<int:matter_id>/",
        documents_add,
        name="documents-add-with-matter",
    ),
    path("documents/edit/<int:document_id>/", documents_edit, name="documents-edit"),
    path(
        "documents/edit-name/<int:document_id>/",
        documents_edit_name,
        name="documents-edit-name",
    ),
    path(
        "documents/delete/<int:document_id>/", documents_delete, name="documents-delete"
    ),
    path("documents/filter/", documents_filter, name="documents-filter"),
    path(
        "documents/filter/label/<int:label_id>/",
        documents_filter_label,
        name="documents-filter-label",
    ),
    path(
        "documents/filter/category/",
        documents_filter_category,
        name="documents-filter-category-clear",
    ),
    path(
        "documents/filter/category/<str:category>/",
        documents_filter_category,
        name="documents-filter-category",
    ),
    path(
        "documents/filter/keyword/",
        documents_filter_keyword,
        name="documents-filter-keyword",
    ),
    path(
        "documents/filter/importance/<int:importance_value>/",
        documents_filter_importance,
        name="documents-filter-importance",
    ),
    path("documents/sort/<str:order>/", documents_sort, name="documents-sort"),
    path(
        "documents/download/<int:document_id>/",
        download_document,
        name="documents-download",
    ),
    # Inline editing
    path(
        "documents/<int:document_id>/date/",
        document_date,
        name="document-date",
    ),
    path(
        "documents/<int:document_id>/category/<str:category>/",
        document_category,
        name="document-category",
    ),
    path(
        "documents/<int:document_id>/proceeding/<int:proceeding_id>/",
        document_proceeding,
        name="document-proceeding",
    ),
    path(
        "documents/<int:document_id>/importance/<int:importance>/",
        document_importance,
        name="document-importance",
    ),
    path(
        "documents/get-proceedings-and-labels/",
        get_proceedings_and_labels,
        name="get-proceedings-and-labels",
    ),
    path("documents/bulk-update/", bulk_documents_update, name="documents-bulk-update"),
    path(
        "documents/toggle-select/<int:document_id>/",
        toggle_document_select,
        name="documents-toggle-select",
    ),
    path(
        "documents/clear-selection/",
        clear_document_selection,
        name="documents-clear-selection",
    ),
    path("documents/row/<int:document_id>/", document_row, name="document-row"),
    path("documents/ocr-badge/<int:document_id>/", ocr_badge, name="ocr-badge"),
    # Labels
    path("case/labels/", labels_index, name="labels-index"),
    path("case/labels/list/", labels_list, name="labels-list"),
    path("case/labels/add/", add_label, name="add-label"),
    path("case/labels/edit/<int:label_id>/", edit_label, name="edit-label"),
    path("case/labels/delete/<int:label_id>/", delete_label, name="delete-label"),
    path("case/labels/filter/", labels_filter, name="filter-labels"),
    path("case/labels/sort/<str:order>/", labels_sort, name="sort-labels"),
    # Label application (to documents/highlights/facts)
    path(
        "case/labels/apply/<str:object_type>/<int:object_id>/",
        labels_apply_modal,
        name="labels-apply-modal",
    ),
    path(
        "case/labels/search/<str:object_type>/<int:object_id>/",
        labels_search,
        name="labels-search",
    ),
    path(
        "case/labels/add-to/<str:object_type>/<int:object_id>/",
        add_label_to,
        name="add-label-to",
    ),
    path(
        "case/labels/remove-from/<str:object_type>/<int:object_id>/",
        remove_label_from,
        name="remove-label-from",
    ),
    path(
        "case/labels/create-and-apply/<str:object_type>/<int:object_id>/",
        labels_create_and_apply,
        name="labels-create-and-apply",
    ),
    # PDF Viewer
    path("documents/view/<int:document_id>/", document_viewer, name="viewer"),
    path("documents/serve/<int:document_id>/", serve_document, name="serve"),
    # OCR endpoints
    path("documents/ocr-status/<int:document_id>/", ocr_status, name="ocr-status"),
    path("documents/retry-ocr/<int:document_id>/", retry_ocr, name="retry-ocr"),
    # Highlight endpoints
    path(
        "documents/<int:document_id>/highlights/add/",
        add_highlight,
        name="add-highlight",
    ),
    path(
        "case/highlights/<int:highlight_id>/edit/",
        edit_highlight,
        name="edit-highlight",
    ),
    path(
        "case/highlights/<int:highlight_id>/delete/",
        delete_highlight,
        name="delete-highlight",
    ),
    path(
        "case/highlights/<int:highlight_id>/importance/<int:importance>/",
        highlight_importance,
        name="highlight-importance",
    ),
    path(
        "case/highlights/<int:highlight_id>/",
        highlight_link,
        name="highlight-link",
    ),
    # Highlights subapp
    path("case/highlights/", highlights_index, name="highlights-index"),
    path(
        "case/highlights/for/<int:document_id>/",
        highlights_for_document,
        name="highlights-for-document",
    ),
    path("case/highlights/list/", highlights_list, name="highlights-list"),
    path("case/highlights/filter/", highlights_filter, name="highlights-filter"),
    path(
        "case/highlights/filter/document/",
        highlights_filter_document,
        name="highlights-filter-document",
    ),
    path(
        "case/highlights/filter/document/<int:document_id>/",
        highlights_filter_document,
        name="highlights-filter-document",
    ),
    path(
        "case/highlights/filter/keyword/",
        highlights_filter_keyword,
        name="highlights-filter-keyword",
    ),
    path(
        "case/highlights/filter/importance/<int:importance_value>/",
        highlights_filter_importance,
        name="highlights-filter-importance",
    ),
    path(
        "case/highlights/filter/sort/<str:order>/",
        highlights_filter_sort,
        name="highlights-filter-sort",
    ),
    path(
        "case/highlights/filter/default/",
        highlights_filter_default,
        name="highlights-filter-default",
    ),
    # Facts subapp
    path("case/facts/", facts_index, name="facts-index"),
    path("case/facts/list/", facts_list, name="facts-list"),
    path("case/facts/filter/", facts_filter, name="facts-filter"),
    path(
        "case/facts/filter/keyword/",
        facts_filter_keyword,
        name="facts-filter-keyword",
    ),
    path(
        "case/facts/filter/importance/<int:importance_value>/",
        facts_filter_importance,
        name="facts-filter-importance",
    ),
    path("case/facts/sort/<str:order>/", facts_sort, name="facts-sort"),
    path("case/facts/add/", facts_add, name="facts-add"),
    path("case/facts/<int:fact_id>/edit/", facts_edit, name="facts-edit"),
    path(
        "case/facts/<int:fact_id>/delete/",
        facts_delete,
        name="facts-delete",
    ),
    path("case/facts/print/", facts_print, name="facts-print"),
    path("case/facts/pdf/", facts_pdf, name="facts-pdf"),
    path(
        "case/facts/<int:fact_id>/edit-description/",
        facts_edit_description,
        name="facts-edit-description",
    ),
    path(
        "case/facts/<int:fact_id>/update-description/",
        facts_update_description,
        name="facts-update-description",
    ),
    path(
        "case/facts/<int:fact_id>/sources/",
        fact_sources_modal,
        name="fact-sources",
    ),
    path(
        "case/facts/<int:fact_id>/sources/search/",
        fact_sources_search,
        name="fact-sources-search",
    ),
    path(
        "case/facts/<int:fact_id>/sources/add/",
        fact_add_source,
        name="fact-add-source",
    ),
    path(
        "case/facts/<int:fact_id>/sources/remove/",
        fact_remove_source,
        name="fact-remove-source",
    ),
    path(
        "case/facts/<int:fact_id>/importance/<int:importance>/",
        fact_importance,
        name="fact-importance",
    ),
    # Search subapp
    path("case/search/", search_index, name="search-index"),
    path("case/search/list/", search_list, name="search-list"),
    path("case/search/results/", search_results, name="search-results"),
    path("case/search/query/", search_query, name="search-query"),
    path("case/search/filter/", search_filter, name="search-filter"),
    path(
        "case/search/filter/type/",
        search_filter_type,
        name="search-filter-type-clear",
    ),
    path(
        "case/search/filter/type/<str:result_type>/",
        search_filter_type,
        name="search-filter-type",
    ),
    path("case/search/clear/", search_clear, name="search-clear"),
]
