# Generated by Django 4.1.10 on 2025-08-05 22:25

from django.db import migrations


def update_practice_area_names(apps, schema_editor):
    """Update practice area names to new values"""
    Intake = apps.get_model('intakes', 'Intake')

    # Mapping of old names to new names
    name_mapping = {
        'Boundary Dispute': 'Boundary',
        'Title Dispute': 'Title',
        'Quiet Title': 'QT',
        'Home Defect': 'Fraud',
    }

    # Update each practice area
    for old_name, new_name in name_mapping.items():
        Intake.objects.filter(practice_area=old_name).update(practice_area=new_name)


def reverse_practice_area_names(apps, schema_editor):
    """Reverse the practice area name changes"""
    Intake = apps.get_model('intakes', 'Intake')

    # Reverse mapping
    name_mapping = {
        'Boundary': 'Boundary Dispute',
        'Title': 'Title Dispute',
        'QT': 'Quiet Title',
        'Fraud': 'Home Defect',
    }

    # Reverse each practice area
    for new_name, old_name in name_mapping.items():
        Intake.objects.filter(practice_area=new_name).update(practice_area=old_name)


class Migration(migrations.Migration):

    dependencies = [
        ('intakes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            update_practice_area_names,
            reverse_practice_area_names
        ),
    ]