# Generated by Django 4.2.22 on 2025-11-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intakes", "0002_update_practice_area_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="intake",
            name="property_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
