# Generated by Django 4.2.22 on 2025-11-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intakes", "0003_intake_property_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="intake",
            old_name="property_address",
            new_name="disputed_property",
        ),
        migrations.AddField(
            model_name="intake",
            name="value",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
