# Generated by Django 4.2.22 on 2025-11-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intakes", "0004_rename_property_address_intake_disputed_property_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intake",
            name="value",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
