# Generated by Django 4.2.22 on 2025-11-22 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("intakes", "0005_alter_intake_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserIntakeView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_viewed_at", models.DateTimeField(auto_now=True)),
                (
                    "intake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="intakes.intake"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "app_user_intake_view",
                "indexes": [
                    models.Index(
                        fields=["user", "intake"], name="app_user_in_user_id_9d3070_idx"
                    )
                ],
                "unique_together": {("user", "intake")},
            },
        ),
    ]
