# Generated by Django 4.2.26 on 2025-11-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intakes", "0006_userintakeview"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
