# Generated by Django 4.2.29 on 2026-04-02 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intakes', '0010_intake_created_at_intake_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalintake',
            name='importance',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='intake',
            name='importance',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
