# Generated by Django 4.2.22 on 2025-08-08 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0009_remove_emphasis_field"),
        ("documents", "0002_document_matter_alter_document_id_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="matter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="matters.matter",
            ),
        ),
    ]
