# Generated by Django 4.2.22 on 2025-09-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_document_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="category",
            field=models.CharField(
                choices=[
                    ("Evidence", "Evidence"),
                    ("Record", "Record"),
                    ("Correspondence", "Correspondence"),
                ],
                default="Evidence",
                max_length=20,
            ),
        ),
    ]
