# Generated by Django 4.2.26 on 2025-12-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0013_label_color_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="highlight",
            name="trim_back",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="highlight",
            name="trim_front",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
