# Generated by Django 4.2.26 on 2025-12-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0014_add_highlight_trim_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="highlight",
            name="trim_back",
        ),
        migrations.RemoveField(
            model_name="highlight",
            name="trim_front",
        ),
    ]
