# Generated by Django 4.2.26 on 2025-12-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0015_remove_highlight_trim_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="abbreviated_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
