# Generated by Django 4.2.26 on 2025-12-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0016_add_document_abbreviated_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="highlight",
            name="paragraph_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
