# Generated by Django 4.2.26 on 2025-12-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0017_add_highlight_paragraph_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="highlight",
            name="paragraph_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
