# Generated by Django 4.2.26 on 2025-12-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0020_ai_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="llm",
            field=models.CharField(
                choices=[
                    ("claude", "Claude"),
                    ("gemini-flash", "Gemini Flash"),
                    ("gemini-pro", "Gemini Pro"),
                ],
                default="claude",
                max_length=20,
            ),
        ),
    ]
