# Generated by Django 4.2.26 on 2025-12-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0026_add_note_category_viewed_date"),
    ]

    operations = [
        # State-only deletion - the table stays in the database
        # and will be managed by the notes app
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Note",
                ),
            ],
            database_operations=[],
        ),
    ]
