# Generated by Django 4.2.26 on 2025-12-19 15:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0027_add_proceeding_nickname"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("case", "0027_delete_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="Witness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "alignment",
                    models.CharField(
                        choices=[
                            ("friendly", "Friendly"),
                            ("neutral", "Neutral"),
                            ("hostile", "Hostile"),
                        ],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                ("knowledge", models.TextField(blank=True)),
                (
                    "importance",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="witnesses",
                        to="matters.matter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "app_witness",
                "ordering": ["name"],
            },
        ),
    ]
