# Generated by Django 4.2.26 on 2025-12-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0028_add_witness_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="witness",
            name="affiliation",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
