# Generated by Django 4.2.26 on 2026-01-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0033_add_caselaw_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="llm",
            field=models.CharField(
                choices=[
                    ("claude", "Claude"),
                    ("gemini-flash", "Gemini Flash"),
                    ("gemini-pro", "Gemini Pro"),
                    ("gemini-3-pro", "Gemini 3 Pro"),
                ],
                default="gemini-3-pro",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalconversation",
            name="llm",
            field=models.CharField(
                choices=[
                    ("claude", "Claude"),
                    ("gemini-flash", "Gemini Flash"),
                    ("gemini-pro", "Gemini Pro"),
                    ("gemini-3-pro", "Gemini 3 Pro"),
                ],
                default="gemini-3-pro",
                max_length=20,
            ),
        ),
    ]
