# Generated by Django 4.2.26 on 2026-01-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0034_alter_conversation_llm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="llm",
            field=models.CharField(
                choices=[
                    ("claude", "Claude Sonnet 4"),
                    ("claude-opus", "Claude Opus 4.5"),
                    ("gemini-flash", "Gemini 2.5 Flash"),
                    ("gemini-pro", "Gemini 2.5 Pro"),
                    ("gemini-3-pro", "Gemini 3 Pro"),
                ],
                default="gemini-3-pro",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalconversation",
            name="llm",
            field=models.CharField(
                choices=[
                    ("claude", "Claude Sonnet 4"),
                    ("claude-opus", "Claude Opus 4.5"),
                    ("gemini-flash", "Gemini 2.5 Flash"),
                    ("gemini-pro", "Gemini 2.5 Pro"),
                    ("gemini-3-pro", "Gemini 3 Pro"),
                ],
                default="gemini-3-pro",
                max_length=20,
            ),
        ),
    ]
