# Generated by Django 4.2.26 on 2026-01-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0035_alter_conversation_llm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caselaw",
            name="importance",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="historicalcaselaw",
            name="importance",
            field=models.IntegerField(default=5),
        ),
    ]
