# Generated by Django 4.2.26 on 2026-01-04 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0036_add_importance_to_caselaw"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="highlight",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="highlight",
            name="caselaw",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlights",
                to="case.caselaw",
            ),
        ),
        migrations.AddField(
            model_name="highlight",
            name="char_offset",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalhighlight",
            name="caselaw",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="case.caselaw",
            ),
        ),
        migrations.AddField(
            model_name="historicalhighlight",
            name="char_offset",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="highlight",
            name="coordinates",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="highlight",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlights",
                to="case.document",
            ),
        ),
        migrations.AlterField(
            model_name="highlight",
            name="page_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalhighlight",
            name="coordinates",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalhighlight",
            name="page_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="highlight",
            index=models.Index(
                fields=["caselaw", "char_offset"], name="app_documen_caselaw_bcbfda_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="highlight",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("caselaw__isnull", True), ("document__isnull", False)),
                    models.Q(("caselaw__isnull", False), ("document__isnull", True)),
                    _connector="OR",
                ),
                name="highlight_has_one_source",
            ),
        ),
    ]
