# Generated by Django 4.2.26 on 2026-01-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0038_add_caselaw_include_in_ai"),
    ]

    operations = [
        migrations.AddField(
            model_name="caselaw",
            name="first_page",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="caselaw",
            name="parallel_page",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="caselaw",
            name="parallel_reporter",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="caselaw",
            name="parallel_volume",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="caselaw",
            name="reporter",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="caselaw",
            name="short_form",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="caselaw",
            name="volume",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="historicalcaselaw",
            name="first_page",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="historicalcaselaw",
            name="parallel_page",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="historicalcaselaw",
            name="parallel_reporter",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="historicalcaselaw",
            name="parallel_volume",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="historicalcaselaw",
            name="reporter",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="historicalcaselaw",
            name="short_form",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="historicalcaselaw",
            name="volume",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
