# Generated by Django 4.2.26 on 2026-01-05 04:48

import re

from django.db import migrations


def parse_citations(apps, schema_editor):
    """Parse existing citation strings into structured fields."""
    CaseLaw = apps.get_model("case", "CaseLaw")

    for case_law in CaseLaw.objects.all():
        if case_law.citation and not case_law.volume:
            # Common pattern: "123 F.3d 456" or "410 U.S. 113"
            match = re.match(
                r"(\d+)\s+([A-Za-z0-9.\s]+?)\s+(\d+)", case_law.citation.strip()
            )
            if match:
                case_law.volume = match.group(1)
                case_law.reporter = match.group(2).strip()
                case_law.first_page = match.group(3)
                case_law.save(update_fields=["volume", "reporter", "first_page"])


def reverse_parse(apps, schema_editor):
    """Reverse: clear structured fields."""
    CaseLaw = apps.get_model("case", "CaseLaw")
    CaseLaw.objects.all().update(volume="", reporter="", first_page="")


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0039_add_structured_citation_fields"),
    ]

    operations = [
        migrations.RunPython(parse_citations, reverse_parse),
    ]
