# Generated by Django 4.2.26 on 2026-01-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0040_alter_conversation_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="include_in_ai",
            field=models.BooleanField(
                default=False, help_text="Include full document text in AI context"
            ),
        ),
        migrations.AddField(
            model_name="historicaldocument",
            name="include_in_ai",
            field=models.BooleanField(
                default=False, help_text="Include full document text in AI context"
            ),
        ),
    ]
