# Generated by Django 4.2.26 on 2026-01-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0042_fix_historicaldocument_include_in_ai"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="include_in_ai",
            field=models.BooleanField(
                default=True, help_text="Include full document text in AI context"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldocument",
            name="include_in_ai",
            field=models.BooleanField(
                default=True, help_text="Include full document text in AI context"
            ),
        ),
    ]
