# Generated by Django 4.2.29 on 2026-03-26 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matters', '0031_matter_members'),
        ('case', '0054_reset_ai_context_to_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_name', models.CharField(blank=True, default='', max_length=500)),
                ('citation', models.CharField(blank=True, default='', max_length=300)),
                ('court', models.CharField(blank=True, default='', max_length=200)),
                ('date_filed', models.CharField(blank=True, default='', max_length=20)),
                ('cluster_id', models.IntegerField(blank=True, null=True)),
                ('brief', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('complete', 'Complete'), ('error', 'Error')], default='pending', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_briefs', to='matters.matter')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_briefs', to='case.researchresult')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
