# Generated by Django 4.2.29 on 2026-03-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0055_casebrief'),
    ]

    operations = [
        migrations.AddField(
            model_name='casebrief',
            name='query_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
