# Generated by Django 4.2.29 on 2026-03-27 01:37

from django.db import migrations


def clear_caselaw_data(apps, schema_editor):
    """Delete all existing case law entries and their associated highlights."""
    Highlight = apps.get_model("case", "Highlight")
    CaseLaw = apps.get_model("case", "CaseLaw")

    Highlight.objects.filter(caselaw__isnull=False).delete()
    CaseLaw.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0057_caselaw_add_summary"),
    ]

    operations = [
        migrations.RunPython(clear_caselaw_data, migrations.RunPython.noop),
    ]
