# Generated by Django 4.2.29 on 2026-03-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0058_clear_legacy_caselaw_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchresult',
            name='relevance',
            field=models.CharField(choices=[('none', 'Not assessed'), ('pending', 'Pending'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('error', 'Error')], default='none', max_length=20),
        ),
    ]
