# Generated by Django 4.2.29 on 2026-04-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0059_researchresult_default_relevance_none'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchresult',
            name='has_negative_history',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
