# Generated by Django 4.2.29 on 2026-04-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0062_migrate_importance_to_normal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalchatattachment',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='historicalchatattachment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalchatattachment',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalchatattachment',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='ChatAttachment',
        ),
        migrations.DeleteModel(
            name='HistoricalChatAttachment',
        ),
    ]
