# Generated by Django 4.2.29 on 2026-04-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0063_remove_historicalchatattachment_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='vet_citations',
            field=models.BooleanField(default=True, help_text='After each response, launch a Gemini Flash job per cited case to check whether the case actually supports what the AI claims.'),
        ),
        migrations.AddField(
            model_name='historicalconversation',
            name='vet_citations',
            field=models.BooleanField(default=True, help_text='After each response, launch a Gemini Flash job per cited case to check whether the case actually supports what the AI claims.'),
        ),
    ]
