# Generated by Django 4.2.29 on 2026-04-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0065_alter_conversation_llm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='witnesses',
            field=models.ManyToManyField(blank=True, related_name='highlights', to='case.witness'),
        ),
    ]
