# Generated by Django 4.2.29 on 2026-06-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_company_jurisdiction'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='invoice_bcc',
            field=models.CharField(blank=True, default='', help_text="Comma-separated addresses BCC'd on every invoice email.", max_length=500),
        ),
    ]
