# Generated by Django 4.2.26 on 2025-11-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("folders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="app",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="folder",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
