# Generated by Django 4.2.17 on 2024-12-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0003_credit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credit",
            name="date",
            field=models.DateField(),
        ),
    ]
