# Generated by Django 4.2.26 on 2025-11-25 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0011_matter_app_matter_status_2f2f4b_idx_and_more"),
        ("invoicing", "0007_creditapplication_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credit",
            name="matter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="matters.matter"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="matter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="matters.matter"
            ),
        ),
    ]
