# Generated by Django 4.2.26 on 2025-11-25 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0008_alter_credit_matter_alter_payment_matter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="amount",
        ),
    ]
