# Generated by Django 4.2.29 on 2026-04-03 21:32

import apps.invoicing.invoices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0014_credit_created_at_credit_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('SENT', 'Sent'), ('DEFERRED', 'Deferred'), ('PAID', 'Paid'), ('UNCOLLECTIBLE', 'Uncollectible'), ('VOID', 'Void')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.invoicing.invoices.models.invoice_upload_path),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('SENT', 'Sent'), ('DEFERRED', 'Deferred'), ('PAID', 'Paid'), ('UNCOLLECTIBLE', 'Uncollectible'), ('VOID', 'Void')], default='DRAFT', max_length=20),
        ),
    ]
