# Generated by Django 4.2.29 on 2026-06-25 10:54
import uuid

from django.db import migrations, models


def backfill_uuids(apps, schema_editor):
    """Give every existing invoice its own uuid before the unique constraint
    lands. AddField applies a single computed default to all rows, so without
    this they would collide on prod."""
    Invoice = apps.get_model("invoicing", "Invoice")
    batch = []
    for inv in Invoice.objects.all().only("id", "uuid").iterator():
        inv.uuid = uuid.uuid4()
        batch.append(inv)
        if len(batch) >= 500:
            Invoice.objects.bulk_update(batch, ["uuid"])
            batch = []
    if batch:
        Invoice.objects.bulk_update(batch, ["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0019_historicalinvoice_date_sent_invoice_date_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(backfill_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='invoice',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True, unique=True
            ),
        ),
    ]
