# Generated by Django 4.2.29 on 2026-06-25 10:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0020_historicalinvoice_uuid_invoice_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
