# Generated by Django 4.2.29 on 2026-06-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0021_alter_historicalinvoice_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='processor',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='processor_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='processor_txn_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='payment',
            name='processor',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='processor_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='processor_txn_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='payment_method',
            field=models.CharField(choices=[('CHECK', 'Check'), ('CARD', 'Card'), ('ACH', 'ACH / eCheck'), ('TRUST', 'Trust'), ('WIRE', 'Wire')], max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CHECK', 'Check'), ('CARD', 'Card'), ('ACH', 'ACH / eCheck'), ('TRUST', 'Trust'), ('WIRE', 'Wire')], max_length=10),
        ),
    ]
