# Generated by Django 4.2.29 on 2026-06-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0022_historicalpayment_processor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetransmission',
            name='cc_email',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='invoicetransmission',
            name='to_email',
            field=models.CharField(max_length=500),
        ),
    ]
