# Generated by Django 4.2.29 on 2026-06-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0024_historicalpaymentrequest_paymentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaymentrequest',
            name='recipient_email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='recipient_email',
            field=models.CharField(max_length=255),
        ),
    ]
