# Generated by Django 4.2.22 on 2025-08-06 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0004_rename_description_to_work_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name='fact',
            old_name='citation',
            new_name='citations',
        ),
    ]
