# Generated by Django 4.2.26 on 2025-11-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0011_matter_app_matter_status_2f2f4b_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settlemententry",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
