# Generated by Django 4.2.26 on 2025-11-25 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0013_convert_user_id_to_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "app_matter_group",
                "ordering": ["order"],
            },
        ),
        migrations.AlterField(
            model_name="relationship",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="matters.role"
            ),
        ),
        migrations.AddField(
            model_name="relationship",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="matters.group",
            ),
        ),
    ]
