# Generated by Django 4.2.26 on 2025-11-25 16:26

from django.db import migrations


def create_groups_and_populate(apps, schema_editor):
    Group = apps.get_model("matters", "Group")
    Relationship = apps.get_model("matters", "Relationship")

    # Create the four groups
    client_group = Group.objects.create(name="Client", order=1)
    adversary_group = Group.objects.create(name="Adversary", order=2)
    court_group = Group.objects.create(name="Court", order=3)
    other_group = Group.objects.create(name="Other", order=4)

    # Populate group field on all existing relationships
    for relationship in Relationship.objects.select_related("role").all():
        role_name = relationship.role.name.lower()
        if "client" in role_name:
            relationship.group = client_group
        elif "adversary" in role_name:
            relationship.group = adversary_group
        elif "court" in role_name:
            relationship.group = court_group
        else:
            relationship.group = other_group
        relationship.save()


def reverse_migration(apps, schema_editor):
    Group = apps.get_model("matters", "Group")
    Relationship = apps.get_model("matters", "Relationship")

    # Clear group field on all relationships
    Relationship.objects.update(group=None)

    # Delete all groups
    Group.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0014_add_group_model"),
    ]

    operations = [
        migrations.RunPython(create_groups_and_populate, reverse_migration),
    ]
