# Generated by Django 4.2.26 on 2025-11-25 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0015_populate_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationship",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="matters.group"
            ),
        ),
    ]
