# Generated by Django 4.2.26 on 2025-11-25

from django.db import migrations


def remove_group_prefix_from_role_names(apps, schema_editor):
    Role = apps.get_model("matters", "Role")

    # Group prefixes to remove (with trailing space)
    group_prefixes = ["Client ", "Adversary ", "Court ", "Other "]

    for role in Role.objects.all():
        original_name = role.name
        new_name = original_name

        for prefix in group_prefixes:
            if new_name.startswith(prefix):
                new_name = new_name[len(prefix):]
                break  # Only remove one prefix

        # Only save if the name actually changed
        if new_name != original_name:
            role.name = new_name.strip()
            role.save()


def reverse_migration(apps, schema_editor):
    # Cannot reliably reverse this migration
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0017_remove_group_from_role_names"),
    ]

    operations = [
        migrations.RunPython(remove_group_prefix_from_role_names, reverse_migration),
    ]
