# Generated by Django 4.2.26 on 2025-11-25

from django.db import migrations


def merge_duplicate_roles(apps, schema_editor):
    Role = apps.get_model("matters", "Role")
    Relationship = apps.get_model("matters", "Relationship")

    # Fix "(Invoicing)" to "Invoicing"
    Role.objects.filter(name="(Invoicing)").update(name="Invoicing")

    # Find and merge duplicate roles
    from collections import defaultdict

    roles_by_name = defaultdict(list)
    for role in Role.objects.all():
        roles_by_name[role.name].append(role)

    for name, roles in roles_by_name.items():
        if len(roles) > 1:
            # Keep the first role, merge others into it
            keeper = roles[0]
            for duplicate in roles[1:]:
                # Update all relationships to use the keeper role
                Relationship.objects.filter(role=duplicate).update(role=keeper)
                # Delete the duplicate role
                duplicate.delete()


def reverse_migration(apps, schema_editor):
    # Cannot reliably reverse this migration
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0018_remove_group_prefix_from_role_names"),
    ]

    operations = [
        migrations.RunPython(merge_duplicate_roles, reverse_migration),
    ]
