# Generated by Django 4.2.26 on 2025-11-25

from django.db import migrations


def cleanup_roles(apps, schema_editor):
    Role = apps.get_model("matters", "Role")
    Relationship = apps.get_model("matters", "Relationship")

    # Get the target Witness role
    witness_role = Role.objects.filter(name="Witness").first()

    # 1. Migrate "Witness Plaintiff" and "Witness Defendant" to "Witness"
    if witness_role:
        for role_name in ["Witness Plaintiff", "Witness Defendant"]:
            role = Role.objects.filter(name=role_name).first()
            if role:
                Relationship.objects.filter(role=role).update(role=witness_role)
                role.delete()

    # 2. Delete relationships and roles for Invoicing, Other, Unspecified
    for role_name in ["Invoicing", "Other", "Unspecified"]:
        role = Role.objects.filter(name=role_name).first()
        if role:
            Relationship.objects.filter(role=role).delete()
            role.delete()


def reverse_migration(apps, schema_editor):
    # Cannot reliably reverse this migration
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0019_merge_duplicate_roles"),
    ]

    operations = [
        migrations.RunPython(cleanup_roles, reverse_migration),
    ]
