# Generated by Django 4.2.28 on 2026-03-09 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("matters", "0030_historicalmatter_jurisdiction_matter_jurisdiction"),
    ]

    operations = [
        migrations.AddField(
            model_name="matter",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_matters", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
