# Generated by Django 4.2.29 on 2026-04-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0032_matter_billable'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmatter',
            name='billing_type',
            field=models.CharField(choices=[('HOURLY', 'Hourly'), ('FLAT_FEE', 'Flat Fee')], default='HOURLY', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalmatter',
            name='flat_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='billing_type',
            field=models.CharField(choices=[('HOURLY', 'Hourly'), ('FLAT_FEE', 'Flat Fee')], default='HOURLY', max_length=20),
        ),
        migrations.AddField(
            model_name='matter',
            name='flat_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='matter',
            index=models.Index(fields=['billing_type'], name='app_matter_billing_0541fc_idx'),
        ),
    ]
