# Generated by Django 4.2.22 on 2025-11-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0007_remove_task_focus"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Zoom", "Zoom"),
                    ("Virtual", "Virtual"),
                    ("Phone", "Phone"),
                    ("In-person", "In-person"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
