# Generated by Django 4.2.22 on 2025-11-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0008_event_end_time_event_location_event_start_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarSyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calendar_id", models.CharField(max_length=255, unique=True)),
                ("sync_token", models.TextField(blank=True, null=True)),
                ("last_sync_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "app_calendar_sync_state",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
