# Generated by Django 4.2.26 on 2025-11-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0009_calendarsyncstate_event_created_at_event_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="custom_order",
            field=models.DecimalField(
                blank=True, decimal_places=8, default=None, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(default=1),
        ),
    ]
