# Generated by Django 4.2.26 on 2025-11-25 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agenda", "0011_event_app_event_matter__bd27b8_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="user_id",
        ),
        migrations.AddField(
            model_name="event",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
