# Generated by Django 4.2.26 on 2025-11-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0012_convert_user_id_to_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
