# Generated by Django 4.2.29 on 2026-03-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_researchresult_forward_citation_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchresult',
            name='review_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
