# Generated by Django 4.2.29 on 2026-03-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_add_review_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='citationverification',
            name='treatment',
            field=models.CharField(blank=True, choices=[('', ''), ('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('distinguished', 'Distinguished')], default='', max_length=20),
        ),
    ]
